####################################################
# Plot 1 (ccr-rateSigma vs. improvement)           #
# Plot 2 (linkSigma-rateSigma vs. improvement)     #
# Plot 3 (taskWidth-cluSize vs. improvement)       #
# Plot 4 (taskDeg-cluDeg vs. improvement)          #
####################################################

depth:  4
width_min:  1       # [Sept 5]: 1, 2, 3
width_max:  1       # [Sept 5]: 3, 4, 5
ccr:  20            # [Sept 5]: 2, 20, 200
comp_mu:    100       # computation workload
comp_sigma: 0.5
link_comm_sigma:  0.5   # [Sept 5] 0.1,0.5,0.9  #link_comm is in normal distribution. It is the data transmitted on links.
deg_mu: 4           # [Sept 5]: 2, 4, 6
deg_sigma: 0.5
total_num: 10
