 
node_list:
  home: k8sworkersb-ubuntu-s-4vcpu-8gb-0-lon1 
  node1: k8sworkersb-ubuntu-s-4vcpu-8gb-1-sfo2
  node2: 8sworkersb-ubuntu-s-4vcpu-8gb-2-sfo2
  datasource1: k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1
application:
  ports:
    # these ports are to be exposed by app docker containers and also exposed via k8s service
    # available range: 50000-60000
    - 57021
  num_tasks: 26 #base is 19, add 7 everytime adding a new set
  task_list:
    home: home  #TODO
    sources:
      - datasource1
    sinks:
    worker_tasks:
      - name: master
        # node_placement: n2
        inputs_to_wait_for: 9
        output_policy: BATCHED_CUSTOM_ORDER
        children:  # child order determines round robin sequence
          - resnet0
          - resnet1
          - resnet2
          - resnet3
          - resnet4
          - resnet5
          - resnet6
          - resnet7
          - resnet8
          - collage
        infile_prefix: n0
        outfile_prefix: master
        dag_task: True
      - name: resnet0
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet0
        dag_task: True
      - name: resnet1
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet1
        dag_task: True
      - name: resnet2
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet2
        dag_task: True
      - name: resnet3
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet3
        dag_task: True
      - name: resnet4
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet4
        dag_task: True
      - name: resnet5
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet5
        dag_task: True
      - name: resnet6
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet6
        dag_task: True
      - name: resnet7
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet7
        dag_task: True
      - name: resnet8
        inputs_to_wait_for: 1
        output_policy: UNICAST
        children:
          - storeclass1
          - storeclass2
        infile_prefix: master
        outfile_prefix: resnet8
        dag_task: True
      - name: collage
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - decoder
        infile_prefix: master
        outfile_prefix: collage
        dag_task: True
      - name: decoder
        inputs_to_wait_for: 1
        output_policy: NONE
        infile_prefix: collage
        outfile_prefix: decoder
        dag_task: True
      - name: storeclass1
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc1
        infile_prefix: resnet
        outfile_prefix: storeclass1
        dag_task: True
      - name: storeclass2
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - lccenc2
        infile_prefix: resnet
        outfile_prefix: storeclass2
        dag_task: True
      - name: lccenc1
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score1a
          - score1b
          - score1c
        infile_prefix: storeclass1
        outfile_prefix: lccenc1
        dag_task: True
      - name: lccenc2
        inputs_to_wait_for: 4
        output_policy: BATCHED_CUSTOM_ORDER
        children:
          - score2a
          - score2b
          - score2c
        infile_prefix: storeclass2
        outfile_prefix: lccenc2
        dag_task: True
      - name: score1a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1a
        dag_task: True
      - name: score1b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1b
        dag_task: True
      - name: score1c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg1
        infile_prefix: lccenc1
        outfile_prefix: score1c
        dag_task: True
      - name: score2a
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2a
        dag_task: True
      - name: score2b
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2b
        dag_task: True
      - name: score2c
        inputs_to_wait_for: 1
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - preagg2
        infile_prefix: lccenc2
        outfile_prefix: score2c
        dag_task: True
      - name: preagg1
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec1
        infile_prefix: score1
        outfile_prefix: preagg1
        dag_task: True
      - name: preagg2
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - lccdec2
        infile_prefix: score2
        outfile_prefix: preagg2
        dag_task: True
      - name: lccdec1
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg1
        outfile_prefix: lccdec1
        dag_task: True
      - name: lccdec2
        inputs_to_wait_for: 2
        output_policy: POINT_TO_POINT_BROADCAST
        children: 
          - home
        infile_prefix: preagg2
        outfile_prefix: lccdec2
        dag_task: True
     