schedule = ['master',
 {'collage': ['1', 'true'],
  'lccdec1': ['2', 'true', 'home'],
  'lccdec2': ['2', 'true', 'home'],
  'lccdec3': ['2', 'true', 'home'],
  'lccdec4': ['2', 'true', 'home'],
  'lccdec5': ['2', 'true', 'home'],
  'lccenc1': ['4', 'ordered', 'score1a', 'score1b', 'score1c'],
  'lccenc2': ['4', 'ordered', 'score2a', 'score2b', 'score2c'],
  'lccenc3': ['4', 'ordered', 'score3a', 'score3b', 'score3c'],
  'lccenc4': ['4', 'ordered', 'score4a', 'score4b', 'score4c'],
  'lccenc5': ['4', 'ordered', 'score5a', 'score5b', 'score5c'],
  'master': ['9',
             'ordered',
             'collage',
             'resnet0',
             'resnet1',
             'resnet2',
             'resnet3',
             'resnet4',
             'resnet5',
             'resnet6',
             'resnet7',
             'resnet8'],
  'preagg1': ['1', 'true', 'lccdec1'],
  'preagg2': ['1', 'true', 'lccdec2'],
  'preagg3': ['1', 'true', 'lccdec3'],
  'preagg4': ['1', 'true', 'lccdec4'],
  'preagg5': ['1', 'true', 'lccdec5'],
  'resnet0': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet1': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet2': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet3': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet4': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet5': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet6': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet7': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet8': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'score1a': ['1', 'true', 'preagg1'],
  'score1b': ['1', 'true', 'preagg1'],
  'score1c': ['1', 'true', 'preagg1'],
  'score2a': ['1', 'true', 'preagg2'],
  'score2b': ['1', 'true', 'preagg2'],
  'score2c': ['1', 'true', 'preagg2'],
  'score3a': ['1', 'true', 'preagg3'],
  'score3b': ['1', 'true', 'preagg3'],
  'score3c': ['1', 'true', 'preagg3'],
  'score4a': ['1', 'true', 'preagg4'],
  'score4b': ['1', 'true', 'preagg4'],
  'score4c': ['1', 'true', 'preagg4'],
  'score5a': ['1', 'true', 'preagg5'],
  'score5b': ['1', 'true', 'preagg5'],
  'score5c': ['1', 'true', 'preagg5'],
  'storeclass1': ['1', 'true', 'lccenc1'],
  'storeclass2': ['1', 'true', 'lccenc2'],
  'storeclass3': ['1', 'true', 'lccenc3'],
  'storeclass4': ['1', 'true', 'lccenc4'],
  'storeclass5': ['1', 'true', 'lccenc5']},
 {'collage': ['collage', 'k8sworkersb-ubuntu-s-4vcpu-8gb-2-fra1'],
  'home': ['home', 'k8sworkersb-ubuntu-s-4vcpu-8gb-0-blr1'],
  'lccdec1': ['lccdec1', 'k8sworkersb-ubuntu-s-4vcpu-8gb-6-tor1'],
  'lccdec2': ['lccdec2', 'k8sworkersb-ubuntu-s-4vcpu-8gb-8-tor1'],
  'lccdec3': ['lccdec3', 'k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1'],
  'lccdec4': ['lccdec4', 'k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1'],
  'lccdec5': ['lccdec5', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'lccenc1': ['lccenc1', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'lccenc2': ['lccenc2', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'lccenc3': ['lccenc3', 'k8sworkersb-ubuntu-s-4vcpu-8gb-7-tor1'],
  'lccenc4': ['lccenc4', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'lccenc5': ['lccenc5', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'master': ['master', 'k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1'],
  'preagg1': ['preagg1', 'k8sworkersb-ubuntu-s-4vcpu-8gb-6-tor1'],
  'preagg2': ['preagg2', 'k8sworkersb-ubuntu-s-4vcpu-8gb-8-tor1'],
  'preagg3': ['preagg3', 'k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1'],
  'preagg4': ['preagg4', 'k8sworkersb-ubuntu-s-4vcpu-8gb-4-lon1'],
  'preagg5': ['preagg5', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'resnet0': ['resnet0', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'resnet1': ['resnet1', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'resnet2': ['resnet2', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'resnet3': ['resnet3', 'k8sworkersb-ubuntu-s-4vcpu-8gb-8-tor1'],
  'resnet4': ['resnet4', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'resnet5': ['resnet5', 'k8sworkersb-ubuntu-s-4vcpu-8gb-6-tor1'],
  'resnet6': ['resnet6', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'resnet7': ['resnet7', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'resnet8': ['resnet8', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'score1a': ['score1a', 'k8sworkersb-ubuntu-s-4vcpu-8gb-7-tor1'],
  'score1b': ['score1b', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score1c': ['score1c', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'score2a': ['score2a', 'k8sworkersb-ubuntu-s-4vcpu-8gb-8-tor1'],
  'score2b': ['score2b', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score2c': ['score2c', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score3a': ['score3a', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'score3b': ['score3b', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score3c': ['score3c', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score4a': ['score4a', 'k8sworkersb-ubuntu-s-4vcpu-8gb-9-ams3'],
  'score4b': ['score4b', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score4c': ['score4c', 'k8sworkersb-ubuntu-s-4vcpu-8gb-5-nyc3'],
  'score5a': ['score5a', 'k8sworkersb-ubuntu-s-4vcpu-8gb-6-tor1'],
  'score5b': ['score5b', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'score5c': ['score5c', 'k8sworkersb-ubuntu-s-4vcpu-8gb-1-nyc1'],
  'storeclass1': ['storeclass1', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'storeclass2': ['storeclass2', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'storeclass3': ['storeclass3', 'k8sworkersb-ubuntu-s-4vcpu-8gb-9-ams3'],
  'storeclass4': ['storeclass4', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1'],
  'storeclass5': ['storeclass5', 'k8sworkersb-ubuntu-s-4vcpu-8gb-3-fra1']}]

dag = ['master',
 {'collage': ['1', 'true'],
  'lccdec1': ['2', 'true', 'home'],
  'lccdec2': ['2', 'true', 'home'],
  'lccdec3': ['2', 'true', 'home'],
  'lccdec4': ['2', 'true', 'home'],
  'lccdec5': ['2', 'true', 'home'],
  'lccenc1': ['4', 'ordered', 'score1a', 'score1b', 'score1c'],
  'lccenc2': ['4', 'ordered', 'score2a', 'score2b', 'score2c'],
  'lccenc3': ['4', 'ordered', 'score3a', 'score3b', 'score3c'],
  'lccenc4': ['4', 'ordered', 'score4a', 'score4b', 'score4c'],
  'lccenc5': ['4', 'ordered', 'score5a', 'score5b', 'score5c'],
  'master': ['9',
             'ordered',
             'collage',
             'resnet0',
             'resnet1',
             'resnet2',
             'resnet3',
             'resnet4',
             'resnet5',
             'resnet6',
             'resnet7',
             'resnet8'],
  'preagg1': ['1', 'true', 'lccdec1'],
  'preagg2': ['1', 'true', 'lccdec2'],
  'preagg3': ['1', 'true', 'lccdec3'],
  'preagg4': ['1', 'true', 'lccdec4'],
  'preagg5': ['1', 'true', 'lccdec5'],
  'resnet0': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet1': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet2': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet3': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet4': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet5': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet6': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet7': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'resnet8': ['1',
              'exclusive',
              'storeclass1',
              'storeclass2',
              'storeclass3',
              'storeclass4',
              'storeclass5'],
  'score1a': ['1', 'true', 'preagg1'],
  'score1b': ['1', 'true', 'preagg1'],
  'score1c': ['1', 'true', 'preagg1'],
  'score2a': ['1', 'true', 'preagg2'],
  'score2b': ['1', 'true', 'preagg2'],
  'score2c': ['1', 'true', 'preagg2'],
  'score3a': ['1', 'true', 'preagg3'],
  'score3b': ['1', 'true', 'preagg3'],
  'score3c': ['1', 'true', 'preagg3'],
  'score4a': ['1', 'true', 'preagg4'],
  'score4b': ['1', 'true', 'preagg4'],
  'score4c': ['1', 'true', 'preagg4'],
  'score5a': ['1', 'true', 'preagg5'],
  'score5b': ['1', 'true', 'preagg5'],
  'score5c': ['1', 'true', 'preagg5'],
  'storeclass1': ['1', 'true', 'lccenc1'],
  'storeclass2': ['1', 'true', 'lccenc2'],
  'storeclass3': ['1', 'true', 'lccenc3'],
  'storeclass4': ['1', 'true', 'lccenc4'],
  'storeclass5': ['1', 'true', 'lccenc5']}]