node_list:
  home: n0
  node1: n1_or_some_custom_hostname_in_k8s
  node2: n2
  node3: n3
  node4: n4
  node5: n5
application:
  ports:
    # these ports are to be exposed by app docker containers and also exposed via k8s service
    # available range: 50000-60000
    - 57021
  num_tasks: 7
  task_list:
    home: home  #TODO
    sources:
      - datasource0
      - datasource1
      - home
    sinks:
    worker_tasks:
      - name: task0
        node_placement: n2
        inputs_to_wait_for: 1
        output_policy: BATCHED_ROUND_ROBIN
        children:  # child order determines round robin sequence
          - task2
          - task1
        infile_prefix: homeout
        outfile_prefix: outtask0
        dag_task: True
      - name: task1
        inputs_to_wait_for: 1
        output_policy: BATCHED_ROUND_ROBIN
        children:
          - task4
          - task3
          - task6
        infile_prefix: outtask0
        outfile_prefix: outtask1
        dag_task: False
      - name: task2
        inputs_to_wait_for: 1
        output_policy: BATCHED_ROUND_ROBIN
        children:
          - task5
          - task6
        infile_prefix: outtask0
        outfile_prefix: outtask2
        dag_task: True
      - name: task3
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - task6
        infile_prefix: outtask1
        outfile_prefix: outtask3
        dag_task: True
      - name: task4
        inputs_to_wait_for: 3
        output_policy: POINT_TO_POINT_BROADCAST
        children:
          - task6
        infile_prefix: outtask1
        outfile_prefix: outtask4
        dag_task: True
      - name: task5
        inputs_to_wait_for: 2
        output_policy: BATCHED_ROUND_ROBIN
        children: 
        infile_prefix: outtask2
        outfile_prefix: outtask5
        dag_task: False
      - name: task6
        inputs_to_wait_for: 5
        output_policy: BATCHED_ROUND_ROBIN
        children:
          - home
        infile_prefix: outtask
        outfile_prefix: outtask3
        dag_task: True
