jupiter_config:
  # Jupiter subsystems will be deployed in separate k8s namespaces. Using
  # different prefixes allows multiple users to use the same k8s cluster.
  # e.g. prefix "jason" results in namespaces:
  # jason-exec
  # jason-circe
  # jason-profiler
  # jason-mapper
  namespace_prefix: quynh
  # Docker registry prefix for pulling and pushing images. Set to empty string for
  # Docker Hub. Examples: "anrg", "docker.io/anrg", "gcr.io/organization_name", ""
  docker_registry: anrg
  # Choose mapper: "heft", "heft_balance", or "wave" (not yet supported)
  task_mapper: heft
  # Choose CIRCE dispatcher type: "original" (currently the only supported)
  circe: original
node_list:
  # "home" is required. All other names should be "node*" where * is some
  # integer.
  home: workers-s-1vcpu-3gb-0-nyc1
  node1: workers-s-1vcpu-3gb-1-sgp1
  node2: workers-s-1vcpu-3gb-2-fra1
  node3: workers-s-1vcpu-3gb-3-tor1
  node4: workers-s-1vcpu-3gb-4-lon1
application:
  # List of port mappings in format. Used for creating additional k8s services
  # for your application. i.e., "9000:8000" will create a service with port 9000
  # which targets port 8000 in all application containers.
  # Note: [PORT_MAPPINGS] section in jupiter_config.ini cannot be used.
  port_mappings:
  task_list:
    home:
      base_script: home.py
      children:
    nondag_tasks:
    - name: datasource1 # TODO: suggest using dataset name as the name instaed
      dataset: fireengine # TODO: remove dataset/datapath and use name to differentiate in code
      datapath: data/fireengine
      base_script: datasource.py #TODO: create a datasource script
      #this should be a node that jupiter wont schedule nodes on
      k8s_host: workers-s-1vcpu-3gb-5-fra1
    - name: datasource2
      # dataset: schoolbus
      # datapath: data/schoolbus
      # stream_image: docker.io/anrg/streams_home:schoolbus
      base_script: datasource.py
      #this should be a node that jupiter wont schedule nodes on
      k8s_host: workers-s-1vcpu-3gb-6-fra1
    - name: datasource3
      # dataset: whitewolf
      # datapath: data/whitewolf
      # stream_image: docker.io/anrg/streams_home:whitewolf
      base_script: datasource.py
      #this should be a node that jupiter wont schedule nodes on
      k8s_host: workers-s-1vcpu-3gb-7-ams3
    - name: datasource4
      # dataset: hyena
      # datapath: data/hyena
      # stream_image: docker.io/anrg/streams_home:hyena
      base_script: datasource.py
      #this should be a node that jupiter wont schedule nodes on
      k8s_host: workers-s-1vcpu-3gb-8-nyc3
    - name: datasource5
      # dataset: tiger
      # datapath: data/tiger
      # stream_image: docker.io/anrg/streams_home:tiger
      base_script: datasource.py
      #this should be a node that jupiter wont schedule nodes on
      k8s_host: workers-s-1vcpu-3gb-9-lon1
    # Tasks that comprise the application DAG
    dag_tasks:
      - name: master
        # node_placement: n2
        base_script: master.py
        children:  # child order determines round robin sequence
          - resnet0
          - resnet1
          - resnet2
          - resnet3
          - resnet4
          - resnet5
          - resnet6
          - resnet7
          - resnet8
          - collage
      - name: resnet0
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet1
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet2
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet3
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet4
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet5
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet6
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet7
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: resnet8
        base_script: resnet.py
        children:
          - storeclass1
          - storeclass2
          - storeclass3
          - storeclass4
          - storeclass5
      - name: collage
        base_script: collage.py
      - name: storeclass1
        base_script: storeclass.py
        children:
          - lccenc1
      - name: storeclass2
        base_script: storeclass.py
        children:
          - lccenc2
      - name: storeclass3
        base_script: storeclass.py
        children:
          - lccenc3
      - name: storeclass4
        base_script: storeclass.py
        children:
          - lccenc4
      - name: storeclass5
        base_script: storeclass.py
        children:
          - lccenc5
      - name: lccenc1
        base_script: lccenc.py
        children:
          - score1a
          - score1b
          - score1c
      - name: lccenc2
        base_script: lccenc.py
        children:
          - score2a
          - score2b
          - score2c
      - name: lccenc3
        base_script: lccenc.py
        children:
          - score3a
          - score3b
          - score3c
      - name: lccenc4
        base_script: lccenc.py
        children:
          - score4a
          - score4b
          - score4c
      - name: lccenc5
        base_script: lccenc.py
        children:
          - score5a
          - score5b
          - score5c
      - name: score1a
        base_script: score.py
        children:
          - preagg1
      - name: score1b
        base_script: score.py
        children:
          - preagg1
      - name: score1c
        base_script: score.py
        children:
          - preagg1
      - name: score2a
        base_script: score.py
        children:
          - preagg2
      - name: score2b
        base_script: score.py
        children:
          - preagg2
      - name: score2c
        base_script: score.py
        children:
          - preagg2
      - name: score3a
        base_script: score.py
        children:
          - preagg3
      - name: score3b
        base_script: score.py
        children:
          - preagg3
      - name: score3c
        base_script: score.py
        children:
          - preagg3
      - name: score4a
        base_script: score.py
        children:
          - preagg4
      - name: score4b
        base_script: score.py
        children:
          - preagg4
      - name: score4c
        base_script: score.py
        children:
          - preagg4
      - name: score5a
        base_script: score.py
        children:
          - preagg5
      - name: score5b
        base_script: score.py
        children:
          - preagg5
      - name: score5c
        base_script: score.py
        children:
          - preagg5
      - name: preagg1
        base_script: preagg.py
        children:
          - lccdec1
      - name: preagg2
        base_script: preagg.py
        children:
          - lccdec2
      - name: preagg3
        base_script: preagg.py
        children:
          - lccdec3
      - name: preagg4
        base_script: preagg.py
        children:
          - lccdec4
      - name: preagg5
        base_script: preagg.py
        children:
          - lccdec5
      - name: lccdec1
        base_script: lccdec.py
        children:
          - home
      - name: lccdec2
        base_script: lccdec.py
        children:
          - home
      - name: lccdec3
        base_script: lccdec.py
        children:
          - home
      - name: lccdec4
        base_script: lccdec.py
        children:
          - home
      - name: lccdec5
        base_script: lccdec.py
        children:
          - home