#!/bin/bash

make clean

rm -rf source/circe
sphinx-apidoc -o source/circe ../circe 

# rm -rf source/profilers/execution_profiler
# sphinx-apidoc -o source/profilers/execution_profiler ../profilers/execution_profiler

# rm -rf source/profilers/network_resource_profiler
# sphinx-apidoc -o source/profilers/network_resource_profiler/home ../profilers/network_resource_profiler/home
# sphinx-apidoc -o source/profilers/network_resource_profiler/worker ../profilers/network_resource_profiler/worker


# rm -rf source/scripts
# sphinx-apidoc -o source/scripts ../scripts

# rm -rf source/task_mapper/heft
# sphinx-apidoc -o source/task_mapper/heft ../task_mapper/heft

# rm -rf source/task_mapper/wave
# sphinx-apidoc -o source/task_mapper/wave/greedy_wave/home ../wave/greedy_wave/home
# sphinx-apidoc -o source/task_mapper/wave/greedy_wave/worker ../wave/greedy_wave/worker
# sphinx-apidoc -o source/task_mapper/wave/random_wave/home ../wave/random_wave/home
# sphinx-apidoc -o source/task_mapper/wave/random_wave/worker ../wave/random_wave/worker

make html
xdg-open build/html/index.html